config/routes.rb
Rails.application.routes.draw do
  resources :announcements
  resources :tools
  resources :user_permissions

  devise_for :users, controllers: {omniauth_callbacks: "users/omniauth_callbacks"}, :skip => [:registrations] 
  resources :users, :controller => "users" do
    collection do
      patch 'locale_switch'
      patch 'theme_switch'
      get 'lock_user'
      get 'unlock_user'
    end
    post :impersonate, on: :member
    post :stop_impersonating, on: :collection
  end
    
  resources :external_reports

  resources :ridings do
    resources :bank_balances, only: [:new, :create]

    get :voter_contact_stats_current, to: "voter_contact_stats#current"
    get :voter_contact_stats_yesterday, to: "voter_contact_stats#yesterday"
    get :voter_contact_stats_last_7, to: "voter_contact_stats#last_7"
    get :voter_contact_stats_last_30, to: "voter_contact_stats#last_30"

    get :volunteer_stats_current, to: "volunteer_stats#current"
    get :volunteer_stats_yesterday, to: "volunteer_stats#yesterday"
    get :volunteer_stats_last_7, to: "volunteer_stats#last_7"
    get :volunteer_stats_last_30, to: "volunteer_stats#last_30"
  end

  resources :reports, only: [:index] do
    collection do
      get :field_organizer
      get :regional_field
      get :fo_sort
    end
  end
  
  resources :notifications, only: [:index, :show]
  
  
  root "ridings#index"
end

app/models/announcement.rb
class Announcement < ApplicationRecord
	translates :title, :body
	after_commit :send_notification, on: :create

	validates :title_en, :title_fr, :body_en, :body_fr, presence: true

	def send_notification
		if Rails.env.development?
			AnnouncementNotification.with(announcement: self).deliver_later(User.first)
		else
			AnnouncementNotification.with(announcement: self).deliver_later(User.all)
		end
	end
end

app/controllers/announcements_controller.rb
class AnnouncementsController < ApplicationController
  before_action :set_announcement, only: %i[ show edit update destroy ]

  # GET /announcements or /announcements.json
  def index
    @announcements = Announcement.all.order(created_at: :desc)
    authorize @announcements
  end

  # GET /announcements/1 or /announcements/1.json
  def show
  end

  # GET /announcements/new
  def new
    @announcement = Announcement.new
    authorize @announcement
  end

  # GET /announcements/1/edit
  def edit
  end

  # POST /announcements or /announcements.json
  def create
    @announcement = Announcement.new(announcement_params)
    authorize @announcement

    respond_to do |format|
      if @announcement.save
        format.html { redirect_to announcement_url(@announcement), notice: "Announcement was successfully created." }
        format.json { render :show, status: :created, location: @announcement }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @announcement.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /announcements/1 or /announcements/1.json
  def update
    respond_to do |format|
      if @announcement.update(announcement_params)
        format.html { redirect_to announcement_url(@announcement), notice: "Announcement was successfully updated." }
        format.json { render :show, status: :ok, location: @announcement }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @announcement.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /announcements/1 or /announcements/1.json
  def destroy
    @announcement.destroy
    authorize @announcement

    respond_to do |format|
      format.html { redirect_to announcements_url, status: :see_other, notice: "Announcement was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_announcement
      @announcement = Announcement.find(params[:id])
      authorize @announcement
    end

    # Only allow a list of trusted parameters through.
    def announcement_params
      params.require(:announcement).permit(:title_en, :title_fr, :body_en, :body_fr)
    end
end

app/helpers/announcements_helper.rb
module AnnouncementsHelper
end

app/views/announcements/_announcement.html.erb
<div id="<%= dom_id announcement %>" class="bg-white py-5 px-4 sm:pt-6 sm:px-6 shadow-md rounded-lg overflow-hidden border dark:bg-dark-gray-800 dark:border-none dark:shadow-highlight text-gay-900 dark:text-dark-gray-300">
  
  <%= announcement.body %>

</div>

app/views/announcements/_form.html.erb
<%= form_with(model: announcement, data: { turbo_confirm: "Are you sure? This will send notifications to all users." }) do |form| %>
  <%= render "shared/error_messages", resource: announcement %>

  <div class="shadow overflow-hidden sm:rounded-md">
    <div class="px-4 py-5 bg-white sm:p-6 dark:bg-dark-gray-800">

      <div class="grid grid-cols-6 gap-6">
        
        <div class="col-span-6 sm:col-span-3">
          <%= form.label :title_en, class:"block text-sm font-medium text-gray-700 dark:text-gray-300" %>
          <%= form.text_field :title_en, class:"mt-1 focus:ring-brand focus:border-brand block w-full shadow-sm sm:text-sm border-gray-300 rounded-md dark:bg-dark-gray-700 dark:border-dark-gray-600 dark:focus:border-brand-dark dark:focus:ring-brand-dark dark:text-dark-gray-300" %>
        </div>

        <div class="col-span-6 sm:col-span-3">
          <%= form.label :title_fr, class:"block text-sm font-medium text-gray-700 dark:text-gray-300" %>
          <%= form.text_field :title_fr, class:"mt-1 focus:ring-brand focus:border-brand block w-full shadow-sm sm:text-sm border-gray-300 rounded-md dark:bg-dark-gray-700 dark:border-dark-gray-600 dark:focus:border-brand-dark dark:focus:ring-brand-dark dark:text-dark-gray-300" %>
        </div>

        <div class="col-span-6">
          <%= form.label :body_en, class:"block text-sm font-medium text-gray-700 dark:text-gray-300" %>
          <%= form.text_area :body_en, class:"mt-1 focus:ring-brand focus:border-brand block w-full shadow-sm sm:text-sm border-gray-300 rounded-md dark:bg-dark-gray-700 dark:border-dark-gray-600 dark:focus:border-brand-dark dark:focus:ring-brand-dark dark:text-dark-gray-300" %>
        </div>

        <div class="col-span-6">
          <%= form.label :body_fr, class:"block text-sm font-medium text-gray-700 dark:text-gray-300" %>
          <%= form.text_area :body_fr, class:"mt-1 shadow-sm focus:ring-brand focus:border-brand block w-full sm:text-sm border border-gray-300 rounded-md dark:bg-dark-gray-700 dark:border-dark-gray-600 dark:focus:border-brand-dark dark:focus:ring-brand-dark dark:text-dark-gray-300" %>
        </div>

      </div>
    </div>

    <div class="text-right">
      <div class="form-group px-4 py-3 bg-gray-50 text-right sm:px-6 dark:bg-dark-gray-700">

        <%= form.submit "Save", class:"inline-flex justify-center py-2 px-4 border border-transparent shadow-sm text-sm font-medium rounded-md text-white bg-brand focus:outline-none focus:ring-2 focus:ring-offset-2 hover:bg-brand-medium ring-brand dark:bg-brand-dark dark:text-dark-gray-300 dark:focus:ring-brand-dark dark:hover:bg-brand-medium" %>

      </div>
  </div>
  </div>
<% end %>

app/views/announcements/edit.html.erb
<h1>Editing announcement</h1>

<%= render "form", announcement: @announcement %>

<br>

<div>
  <%= link_to "Show this announcement", @announcement %> |
  <%= link_to "Back to announcements", announcements_path %>
</div>

app/views/announcements/index.html.erb
<% content_for :page_title do %>
  Announcements
<% end %>

<% content_for :page_buttons do %>
  <% if current_user.admin? %>
    <%= link_to "New announcement", new_announcement_path, class: "inline-flex items-center px-4 py-2 border border-brand-dark rounded-md shadow-sm text-sm font-medium text-white bg-brand hover:bg-brand-medium focus:outline-none focus:ring-2 focus:ring-offset-2 ring-brand dark:bg-brand-medium dark:hover:bg-brand-dark dark:ring-brand-dark dark:ring-offset-dark-gray-900" %>
  <% end %>
<% end %>

<% if @announcements.empty? %>
  <div class="bg-white shadow overflow-hidden sm:rounded-md dark:bg-dark-gray-800 dark:shadow-highlight">
    <div class="my-8 text-center">
      <svg xmlns="http://www.w3.org/2000/svg" class="mx-auto h-12 w-12 text-brand" fill="none" viewBox="0 0 24 24" stroke="currentColor">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M11 5.882V19.24a1.76 1.76 0 01-3.417.592l-2.147-6.15M18 13a3 3 0 100-6M5.436 13.683A4.001 4.001 0 017 6h1.832c4.1 0 7.625-1.234 9.168-3v14c-1.543-1.766-5.067-3-9.168-3H7a3.988 3.988 0 01-1.564-.317z" />
      </svg>

      <h3 class="mt-2 text-sm font-medium text-gray-900 dark:text-dark-gray-300"><%= t("announcements.empty_placeholder") %></h3>
      <p class="mt-1 text-sm text-gray-500 dark:text-dark-gray-400">
        <%= t("announcements.empty_description") %>
      </p>
    </div>
  </div>
<% end %>


<div class="bg-white shadow overflow-hidden sm:rounded-md dark:bg-dark-gray-800 dark:shadow-highlight">
  <ul role="list" class="divide-y divide-gray-200 dark:divide-dark-gray-600">
    <% @announcements.each do |announcement| %>
      <li>
        <%= link_to announcement, class:"block hover:bg-gray-50 dark:hover:bg-dark-gray-700" do %>
          <div class="px-4 py-4 flex items-center sm:px-6">
            <div class="min-w-0 flex-1 sm:flex sm:items-center sm:justify-between">
              <div class="truncate">
                <div class="flex text-sm">
                  <p class="font-medium text-brand truncate"><%= announcement.title %></p>
                </div>
                <div class="mt-2 flex">
                  <div class="flex items-center text-sm text-gray-500 dark:text-dark-gray-400">
                    <!-- Heroicon name: solid/calendar -->
                    <svg class="flex-shrink-0 mr-1.5 h-5 w-5 text-gray-400 dark:text-dark-gray-500" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                      <path fill-rule="evenodd" d="M6 2a1 1 0 00-1 1v1H4a2 2 0 00-2 2v10a2 2 0 002 2h12a2 2 0 002-2V6a2 2 0 00-2-2h-1V3a1 1 0 10-2 0v1H7V3a1 1 0 00-1-1zm0 5a1 1 0 000 2h8a1 1 0 100-2H6z" clip-rule="evenodd" />
                    </svg>
                    <p>
                      <%= announcement.created_at.strftime("%B %d, %Y") %>
                    </p>
                  </div>
                </div>
              </div>

              <div class="text-sm text-gray-900 dark:text-dark-gray-300">
                <%= announcement.body.truncate(100) %>
              </div>

              <div class="mt-4 flex-shrink-0 sm:mt-0 sm:ml-5">
                <div class="inline-flex items-center px-2.5 py-1.5 border border-transparent text-xs font-medium rounded shadow-sm text-white bg-brand hover:bg-brand-medium focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-brand dark:bg-brand-dark dark:hover:bg-brand-medium">
                  View announcement
                </div>
              </div>
            </div>
            <div class="ml-5 flex-shrink-0">
              <!-- Heroicon name: solid/chevron-right -->
              <svg class="h-5 w-5 text-gray-400" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                <path fill-rule="evenodd" d="M7.293 14.707a1 1 0 010-1.414L10.586 10 7.293 6.707a1 1 0 011.414-1.414l4 4a1 1 0 010 1.414l-4 4a1 1 0 01-1.414 0z" clip-rule="evenodd" />
              </svg>
            </div>
          </div>
        <% end %>
      </li>
    <% end %>
  </ul>
</div>

app/views/announcements/new.html.erb
<% content_for :page_title do %>
  New Announcement
<% end %>

<%= render "form", announcement: @announcement %>

app/views/announcements/show.html.erb
<% content_for :page_title do %>
  <%= @announcement.title %>
<% end %>

<% content_for :page_buttons do %>
  <% if current_user.admin? %>
    <%# link_to "Delete", announcement_path, class: "inline-flex items-center px-4 py-2 border border-brand-dark rounded-md shadow-sm text-sm font-medium text-white bg-brand hover:bg-brand-medium focus:outline-none focus:ring-2 focus:ring-offset-2 ring-brand dark:bg-brand-medium dark:hover:bg-brand-dark dark:ring-brand-dark dark:ring-offset-dark-gray-900", data: { turbo_method: 'delete', turbo_confirm: "Are you sure?" } %>
  <% end %>
<% end %>

<%= render @announcement %>