config/routes.rb
Rails.application.routes.draw do
  resources :announcements
  resources :tools
  resources :user_permissions

  devise_for :users, controllers: {omniauth_callbacks: "users/omniauth_callbacks"}, :skip => [:registrations] 
  resources :users, :controller => "users" do
    collection do
      patch 'locale_switch'
      patch 'theme_switch'
      get 'lock_user'
      get 'unlock_user'
    end
    post :impersonate, on: :member
    post :stop_impersonating, on: :collection
  end
    
  resources :external_reports

  resources :ridings do
    resources :bank_balances, only: [:new, :create]

    get :voter_contact_stats_current, to: "voter_contact_stats#current"
    get :voter_contact_stats_yesterday, to: "voter_contact_stats#yesterday"
    get :voter_contact_stats_last_7, to: "voter_contact_stats#last_7"
    get :voter_contact_stats_last_30, to: "voter_contact_stats#last_30"

    get :volunteer_stats_current, to: "volunteer_stats#current"
    get :volunteer_stats_yesterday, to: "volunteer_stats#yesterday"
    get :volunteer_stats_last_7, to: "volunteer_stats#last_7"
    get :volunteer_stats_last_30, to: "volunteer_stats#last_30"
  end

  resources :reports, only: [:index] do
    collection do
      get :field_organizer
      get :regional_field
      get :fo_sort
    end
  end
  
  resources :notifications, only: [:index, :show]
  
  
  root "ridings#index"
end

app/models/external_report.rb
class ExternalReport < ApplicationRecord
	has_many :riding_external_reports, dependent: :destroy
	translates :name, :description

  	validates :name_en, :name_fr, :description_en, :description_fr, presence: true
end

app/controllers/external_reports_controller.rb
class ExternalReportsController < ApplicationController
  before_action :set_external_report, only: %i[ show edit update destroy ]

  # GET /external_reports or /external_reports.json
  def index
    @external_reports = ExternalReport.all
    authorize @external_reports
  end

  # GET /external_reports/1 or /external_reports/1.json
  def show
  end

  # GET /external_reports/new
  def new
    @external_report = ExternalReport.new
    authorize @external_report
  end

  # GET /external_reports/1/edit
  def edit
  end

  # POST /external_reports or /external_reports.json
  def create
    @external_report = ExternalReport.new(external_report_params)

    respond_to do |format|
      if @external_report.save
        format.html { redirect_to @external_report, notice: "External report was successfully created." }
        format.json { render :show, status: :created, location: @external_report }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @external_report.errors, status: :unprocessable_entity }
      end
    end
    authorize @external_report
  end

  # PATCH/PUT /external_reports/1 or /external_reports/1.json
  def update
    respond_to do |format|
      if @external_report.update(external_report_params)
        format.html { redirect_to @external_report, notice: "External report was successfully updated." }
        format.json { render :show, status: :ok, location: @external_report }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @external_report.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /external_reports/1 or /external_reports/1.json
  def destroy
    @external_report.destroy
    respond_to do |format|
      format.html { redirect_to external_reports_url, notice: "External report was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_external_report
      @external_report = ExternalReport.find(params[:id])
      authorize @external_report
    end

    # Only allow a list of trusted parameters through.
    def external_report_params
      params.require(:external_report).permit(:name_en, :name_fr, :description_en, :description_fr)
    end
end

app/helpers/external_reports_helper.rb
module ExternalReportsHelper
end

app/views/external_reports/_external_report.html.erb
<div id="<%= dom_id external_report %>">
  <p>
    <strong>Name en:</strong>
    <%= external_report.name_en %>
  </p>

  <p>
    <strong>Name fr:</strong>
    <%= external_report.name_fr %>
  </p>

  <p>
    <strong>Description en:</strong>
    <%= external_report.description_en %>
  </p>

  <p>
    <strong>Description fr:</strong>
    <%= external_report.description_fr %>
  </p>

  <p>
    <%= link_to "Show this external report", external_report %>
  </p>
</div>

app/views/external_reports/_form.html.erb
<%= form_with(model: external_report) do |form| %>
  <div class="shadow overflow-hidden sm:rounded-md">
    <div class="px-4 py-5 bg-white sm:p-6">

      <div class="grid grid-cols-6 gap-6">
        
        <div class="col-span-6 sm:col-span-3">
          <%= form.label :name_en, class:"block text-sm font-medium text-gray-700" %>
          <%= form.text_field :name_en, class:"mt-1 focus:ring-indigo-500 focus:border-indigo-500 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md" %>
        </div>

        <div class="col-span-6 sm:col-span-3">
          <%= form.label :name_fr, class:"block text-sm font-medium text-gray-700" %>
          <%= form.text_field :name_fr, class:"mt-1 focus:ring-indigo-500 focus:border-indigo-500 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md" %>
        </div>


        <div class="col-span-6">
          <%= form.label :description_en, class:"block text-sm font-medium text-gray-700" %>
          <%= form.text_field :description_en, class:"mt-1 focus:ring-indigo-500 focus:border-indigo-500 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md" %>
        </div>

        <div class="col-span-6">
          <%= form.label :description_fr, class:"block text-sm font-medium text-gray-700" %>
          <%= form.text_field :description_fr, class:"mt-1 focus:ring-indigo-500 focus:border-indigo-500 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md" %>
        </div>
      </div>
    </div>

    <div class="text-right">

    <div class="form-group px-4 py-3 bg-gray-50 text-right sm:px-6 bg-brand-light-hover">
      <% if external_report.persisted? %>
        <%= button_to 'Destroy', external_report, method: :delete, class:"inline-flex justify-center py-2 px-4 border border-red-500 shadow-sm text-sm font-medium rounded text-red-500 bg-transparent hover:bg-red-500 hover:text-white focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-red-500" %>
      <% end %>

      <%= form.submit "Save", class:"inline-flex justify-center py-2 px-4 border border-transparent shadow-sm text-sm font-medium rounded-md text-white bg-brand focus:outline-none focus:ring-2 focus:ring-offset-2 ring-brand" %>

    </div>

  </div>
</div>
<% end %>

app/views/external_reports/edit.html.erb
<% content_for :page_title do %>
  Editing <%= @external_report.name %> Report
<% end %>

<%= render 'form', external_report: @external_report %>

app/views/external_reports/index.html.erb
<% content_for :page_title do %>
  External Reports
<% end %>

<% content_for :page_buttons do %>
  <% if current_user.admin? %>
    <%= link_to "Add report", new_external_report_path, class: "inline-flex items-center px-4 py-2 border border-brand-dark rounded-md shadow-sm text-sm font-medium text-white bg-brand hover:bg-brand-medium focus:outline-none focus:ring-2 focus:ring-offset-2 ring-brand dark:bg-brand-medium dark:hover:bg-brand-dark dark:ring-brand-dark dark:ring-offset-dark-gray-900" %>
  <% end %>
<% end %>


<div class="flex flex-col">
  <div class="-my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
    <div class="py-2 align-middle inline-block min-w-full sm:px-6 lg:px-8">
      <div class="shadow overflow-hidden border-b border-gray-200 sm:rounded-lg dark:border-dark-gray-600">
        <table class="min-w-full divide-y divide-gray-200 dark:divide-dark-gray-600">
          <thead class="bg-gray-50 dark:bg-dark-gray-700">
            <tr>
              <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider dark:text-dark-gray-300">
                Name
              </th>
              <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider dark:text-dark-gray-300">
                Description
              </th>
            </tr>
          </thead>
          <tbody>
            <% @external_reports.each do |report| %>

            <% if cycle('odd', 'even') == 'odd' %>
              <tr class="bg-white dark:bg-dark-gray-800">
            <% else %>
              <tr class="bg-gray-50 dark:bg-dark-gray-700">
            <% end %>
              <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900 dark:text-dark-gray-300">
                <%= link_to report.name, edit_external_report_path(report) %>
              </td>
              <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500 dark:text-dark-gray-400">
                <%= report.description %>
              </td>
            </tr>

            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/external_reports/new.html.erb
<% content_for :page_title do %>
  New Report
<% end %>

<%= render 'form', external_report: @external_report %>

app/views/external_reports/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @external_report.name %>
</p>

<%= link_to 'Edit', edit_external_report_path(@external_report) %> |
<%= link_to 'Back', external_reports_path %>