config/routes.rb
Rails.application.routes.draw do
  resources :announcements
  resources :tools
  resources :user_permissions

  devise_for :users, controllers: {omniauth_callbacks: "users/omniauth_callbacks"}, :skip => [:registrations] 
  resources :users, :controller => "users" do
    collection do
      patch 'locale_switch'
      patch 'theme_switch'
      get 'lock_user'
      get 'unlock_user'
    end
    post :impersonate, on: :member
    post :stop_impersonating, on: :collection
  end
    
  resources :external_reports

  resources :ridings do
    resources :bank_balances, only: [:new, :create]

    get :voter_contact_stats_current, to: "voter_contact_stats#current"
    get :voter_contact_stats_yesterday, to: "voter_contact_stats#yesterday"
    get :voter_contact_stats_last_7, to: "voter_contact_stats#last_7"
    get :voter_contact_stats_last_30, to: "voter_contact_stats#last_30"

    get :volunteer_stats_current, to: "volunteer_stats#current"
    get :volunteer_stats_yesterday, to: "volunteer_stats#yesterday"
    get :volunteer_stats_last_7, to: "volunteer_stats#last_7"
    get :volunteer_stats_last_30, to: "volunteer_stats#last_30"
  end

  resources :reports, only: [:index] do
    collection do
      get :field_organizer
      get :regional_field
      get :fo_sort
    end
  end
  
  resources :notifications, only: [:index, :show]
  
  
  root "ridings#index"
end

app/models/user.rb
class User < ApplicationRecord
  include UserOnboarding

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, 
         :validatable, :lockable,
         :omniauthable, omniauth_providers: [:google_oauth2]
         
  has_many :user_ridings
  has_many :ridings, through: :user_ridings

  has_many :user_user_permissions, dependent: :destroy
  has_many :user_permissions, through: :user_user_permissions

  has_many :notifications, as: :recipient

  validates :first_name, :last_name, presence: true

  enum user_type: {
    salesforce: 0,
    admin: 1,
    lpc_staff: 2,
  }

  ADMIN_USER_TYPES = [
    ["Salesforce", "salesforce"],
    ["Admin", "admin"],
    ["LPC Staff", "lpc_staff"]
  ]

  LPC_USER_TYPES = [
    ["Salesforce", "salesforce"],
    ["LPC Staff", "salesforce"]
  ]

  USER_TITLES = [
    "DS Admin",
    "Field Organizer",
    "Central Staff",
    "PTB Director"
  ]

  def self.from_omniauth(access_token)
    data = access_token.info
    user = User.where(email: data['email']).first

    # Uncomment the section below if you want users to be created if they don't exist
    # unless user
    #     user = User.create(name: data['name'],
    #        email: data['email'],
    #        password: Devise.friendly_token[0,20]
    #     )
    # end
    user
  end
end

app/controllers/concerns/users/navbar_notifications.rb
module Users
  module NavbarNotifications
    extend ActiveSupport::Concern

    included do
      before_action :set_notifications, if: :user_signed_in?
    end

    def set_notifications
      # Counts to send to native apps
      @account_unread = current_user.notifications.unread.count
      @total_unread = current_user.notifications.unread.count
    end
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # skip_before_action :authenticate_user!

  # def google_oauth2
  #   auth = request.env["omniauth.auth"]
  #   user = User.where(provider: auth["provider"], uid: auth["uid"])
  #           .first_or_initialize(email: auth["info"]["email"])
  #   user.name ||= auth["info"]["name"]
  #   user.save!

  #   user.remember_me = true
  #   sign_in(:user, user)

  #   redirect_to after_sign_in_path_for(user)
  # end

  def google_oauth2
      # You need to implement the method below in your model (e.g. app/models/user.rb)
      @user = User.from_omniauth(request.env['omniauth.auth'])

      if @user.present? && @user.persisted?
        flash[:notice] = I18n.t 'devise.omniauth_callbacks.success', kind: 'Google'
        sign_in_and_redirect @user, event: :authentication
      else
        session['devise.google_data'] = request.env['omniauth.auth'].except('extra') # Removing extra as it can overflow some session stores
        redirect_to new_user_session_url, alert: "Unable to find user."
      end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

  def index
    @users = User.all
    authorize @users
  end

  def show
  end

  def new
    @user = User.new
    authorize @user
  end

  def edit
  end

  def create
    @user = User.new(user_params)
    authorize @user

    # generate secure password as we'll only use google sign in
    password = Devise.friendly_token
    @user.password = password
    @user.password_confirmation = password

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy
    authorize @user
    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def locale_switch
    if current_user.preferred_language == "en"
      current_user.update(preferred_language: "fr")
    else
      current_user.update(preferred_language: "en")
    end

    redirect_back fallback_location: root_path
  end

  def theme_switch
    if current_user.theme == "light"
      if current_user.update(theme: "dark")
        redirect_back fallback_location: root_path
      end
    else
      if current_user.update(theme: "light")
        redirect_back fallback_location: root_path
      end
    end
  end

  def lock_user
    user = User.find(params[:lock_user_id])
    user.lock_access!

    redirect_to user
  end

  def unlock_user
    user = User.find(params[:lock_user_id])
    user.unlock_access!

    redirect_to user
  end

  def impersonate
    user = User.find(params[:id])
    authorize :user, :impersonate?

    impersonate_user(user)
    redirect_to root_path
  end

  def stop_impersonating
    authorize :user, :stop_impersonating?
    stop_impersonating_user
    redirect_to root_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
      authorize @user
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation,
        :user_type, :title, user_permission_ids:[], riding_ids:[])
    end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>

  <%= render "shared/error_messages", resource: user %>

  <div class="shadow overflow-hidden sm:rounded-md">
    <div class="px-4 py-5 bg-white sm:p-6 dark:bg-dark-gray-800">

      <div class="grid grid-cols-6 gap-6">
        
        <div class="col-span-6 sm:col-span-3">
          <%= form.label :first_name, class:"block text-sm font-medium text-gray-700 dark:text-gray-300" %>
          <%= form.text_field :first_name, class:"mt-1 focus:ring-brand focus:border-brand block w-full shadow-sm sm:text-sm border-gray-300 rounded-md dark:bg-dark-gray-700 dark:border-dark-gray-600 dark:focus:border-brand-dark dark:focus:ring-brand-dark dark:text-dark-gray-300" %>
        </div>

        <div class="col-span-6 sm:col-span-3">
          <%= form.label :last_name, class:"block text-sm font-medium text-gray-700 dark:text-gray-300" %>
          <%= form.text_field :last_name, class:"mt-1 focus:ring-brand focus:border-brand block w-full shadow-sm sm:text-sm border-gray-300 rounded-md dark:bg-dark-gray-700 dark:border-dark-gray-600 dark:focus:border-brand-dark dark:focus:ring-brand-dark dark:text-dark-gray-300" %>
        </div>


        <div class="col-span-6 sm:col-span-3">
          <%= form.label :email, class:"block text-sm font-medium text-gray-700 dark:text-gray-300" %>
          <%= form.email_field :email, class:"mt-1 focus:ring-brand focus:border-brand block w-full shadow-sm sm:text-sm border-gray-300 rounded-md dark:bg-dark-gray-700 dark:border-dark-gray-600 dark:focus:border-brand-dark dark:focus:ring-brand-dark dark:text-dark-gray-300" %>
        </div>

        <% if current_user.admin? %> 
          <div class="col-span-6 sm:col-span-3">
            <%= form.label :user_type, class:"block text-sm font-medium text-gray-700 dark:text-gray-300" %>
            <%= form.select :user_type, options_for_select(User::ADMIN_USER_TYPES, form.object.user_type), {}, { class: "mt-1 block w-full pl-3 pr-10 py-2 text-base border-gray-300 focus:outline-none focus:ring-brand focus:border-brand sm:text-sm rounded dark:bg-dark-gray-700 dark:border-dark-gray-600 dark:focus:border-brand-dark dark:focus:ring-brand-dark dark:text-dark-gray-300" } %>
          </div>
        <% elsif current_user.user_user_permissions.map{|p| p.user_permission.name}.include? "Create Users" %>
          <div class="col-span-6 sm:col-span-3">
            <%= form.label :user_type, class:"block text-sm font-medium text-gray-700" %>

            <%= form.select :user_type, options_for_select(User::LPC_USER_TYPES, form.object.user_type), {}, { class: "mt-1 block w-full pl-3 pr-10 py-2 text-base border-gray-300 focus:outline-none focus:ring-brand focus:border-brand sm:text-sm rounded dark:bg-dark-gray-700 dark:border-dark-gray-600 dark:focus:border-brand-dark dark:focus:ring-brand-dark dark:text-dark-gray-300" } %>

          </div>
        <% end %>

        <div class="col-span-6 sm:col-span-3">
          <%= form.label :title, class:"block text-sm font-medium text-gray-700 dark:text-gray-300" %>

          <%= form.select :title, options_for_select(User::USER_TITLES, form.object.title), {}, { class: "mt-1 block w-full pl-3 pr-10 py-2 text-base border-gray-300 focus:outline-none focus:ring-brand focus:border-brand sm:text-sm rounded dark:bg-dark-gray-700 dark:border-dark-gray-600 dark:focus:border-brand-dark dark:focus:ring-brand-dark dark:text-dark-gray-300" } %>
        </div>

        <div class="col-span-6">
          <fieldset class="space-y-5">
            <legend class="block text-sm font-medium text-gray-700 dark:text-gray-300">Permissions</legend>

          <%= form.collection_check_boxes(:user_permission_ids, UserPermission.all, :id, :name) do |permission| %>

          
            <div class="relative flex items-start">
              <div class="flex items-center h-5">
                <%= permission.check_box(class: "focus:ring-brand h-4 w-4 text-brand border-gray-300 rounded dark:focus:ring-brand-dark dark:text-brand-dark dark:bg-dark-gray-700 dark:border-dark-gray-600 dark:checked:bg-brand-dark dark:checked:border-brand-dark") %>
              </div>
              <div class="ml-3 text-sm">
                <%= permission.label(class: "font-medium text-gray-700 dark:text-gray-300") %>
              </div>
            </div>
            <% end %>
          </fieldset>
        </div>

        <div class="mt-6 col-span-6" data-controller="checkbox-select-all" >
          <legend class="block text-sm font-medium text-gray-700 dark:text-gray-300">Ridings</legend>

          <div class="mt-5 relative flex items-start">
            <div class="flex items-center h-5">
              <input type="checkbox" class="focus:ring-brand h-4 w-4 text-brand border-gray-300 rounded dark:focus:ring-brand-dark dark:text-brand-dark dark:bg-dark-gray-700 dark:border-dark-gray-600 dark:checked:bg-brand-dark dark:checked:border-brand-dark dark:indeterminate:bg-brand-dark dark:indeterminate:border-brand-dark" data-checkbox-select-all-target="checkboxAll" id="ridingSelectAll"/>
            </div>
            <div class="ml-3 text-sm">
              <label class="font-medium text-gray-700 dark:text-gray-300" for="ridingSelectAll">Select All / Deselect All</label>
            </div>
          </div>

          <fieldset class="mt-4 grid grid-cols-3 gap-4">

          <%= form.collection_check_boxes(:riding_ids, Riding.all.order(riding_code: :asc), :id, :name) do |riding| %>

          
            <div class="relative flex items-start">
              <div class="flex items-center h-5">
                <%= riding.check_box(class: "focus:ring-brand h-4 w-4 text-brand border-gray-300 rounded dark:focus:ring-brand-dark dark:text-brand-dark dark:bg-dark-gray-700 dark:border-dark-gray-600 dark:checked:bg-brand-dark dark:checked:border-brand-dark",  data: { checkbox_select_all_target: 'checkbox' }) %>
              </div>
              <div class="ml-3 text-sm">
                <%= riding.label(class: "font-medium text-gray-700 dark:text-gray-300") do %>
                  <%= riding.object.name %> - <%= riding.object.riding_code %>
                <% end %>
              </div>
            </div>
            <% end %>
          </fieldset>
        </div>

      </div>
    </div>

    <div class="text-right">
      <div class="form-group px-4 py-3 bg-gray-50 text-right sm:px-6 dark:bg-dark-gray-700">

        <%= form.submit "Save", class:"inline-flex justify-center py-2 px-4 border border-transparent shadow-sm text-sm font-medium rounded-md text-white bg-brand focus:outline-none focus:ring-2 focus:ring-offset-2 hover:bg-brand-medium ring-brand dark:bg-brand-dark dark:text-dark-gray-300 dark:focus:ring-brand-dark dark:hover:bg-brand-medium" %>

      </div>
  </div>
</div>
<% end %>

app/views/users/edit.html.erb
<% content_for :page_title do %>
  Edit User <%= @user.first_name %> <%= @user.last_name %>
<% end %>

<%= render "form", user: @user %>

app/views/users/index.html.erb
<% content_for :page_title do %>
  Users
<% end %>

<% content_for :page_buttons do %>
  <% if current_user.admin? %>
    <%= link_to "Add user", new_user_path, class: "inline-flex items-center px-4 py-2 border border-brand-dark rounded-md shadow-sm text-sm font-medium text-white bg-brand hover:bg-brand-medium focus:outline-none focus:ring-2 focus:ring-offset-2 ring-brand dark:bg-brand-medium dark:hover:bg-brand-dark dark:ring-brand-dark dark:ring-offset-dark-gray-900" %>
  <% end %>
<% end %>

<div class="flex flex-col">
  <div class="-my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
    <div class="py-2 align-middle inline-block min-w-full sm:px-6 lg:px-8">
      <div class="shadow overflow-hidden border-b border-gray-200 sm:rounded-lg dark:border-dark-gray-600">
          <table class="min-w-full divide-y divide-gray-200 dark:divide-dark-gray-600">
            <thead class="bg-gray-50 dark:bg-dark-gray-700">
              <tr>
                <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider dark:text-dark-gray-300">
                  ID
                </th>
                <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider dark:text-dark-gray-300">
                  Name
                </th>
                <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider dark:text-dark-gray-300">
                  Account Type
                </th>
                <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider dark:text-dark-gray-300">
                  Email
                </th>
              </tr>
            </thead>
            <tbody>
              <% @users.order('LOWER(last_name)').each do |user| %>

              <% if cycle('odd', 'even') == 'odd' %>
                <tr class="bg-white dark:bg-dark-gray-800">
              <% else %>
                <tr class="bg-gray-50 dark:bg-dark-gray-700">
              <% end %>
                <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500 dark:text-dark-gray-400">
                  <%= user.id %>
                </td>
                <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900 dark:text-dark-gray-300">
                  <%= link_to "#{user.first_name} #{user.last_name}", user %>
                </td>
                <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500 dark:text-dark-gray-400">
                  <%= user.user_type.titleize %>
                </td>
                <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500 dark:text-dark-gray-400">
                  <%= user.email %>
                </td>
              </tr>

              <% end %>
            </tbody>
          </table>
      </div>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<% content_for :page_title do %>
  New User
<% end %>

<%= render "form", user: @user %>

app/views/users/show.html.erb
<% content_for :page_title do %>
  User: <%= @user.first_name %> <%= @user.last_name %>
<% end %>

<% content_for :page_buttons do %>
  <div class="ml-3 relative" x-data="{ open: false }" @keydown.window.escape="open = false" @click.away="open = false">
    <div>
      <button @click="open = !open" class="max-w-xs bg-white rounded-md flex items-center pl-4 pr-2 py-2 border border-gray-300 shadow-sm text-sm font-medium rounded-md text-gray-700 bg-white hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-brand dark:bg-dark-gray-700 dark:text-dark-gray-300 dark:border-dark-gray-600 dark:focus:ring-offset-dark-gray-900 dark:ring-brand-dark" id="user-menu" aria-haspopup="true" x-bind:aria-expanded="open">
        
        Actions
        <svg class="hidden flex-shrink-0 ml-1 h-5 w-5 text-gray-400 lg:block" x-description="Heroicon name: chevron-down" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
				  <path fill-rule="evenodd" d="M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z" clip-rule="evenodd"></path>
				</svg>
      </button>
    </div>

    <div x-show="open" x-description="Profile dropdown panel, show/hide based on dropdown state." x-transition:enter="transition ease-out duration-100" x-transition:enter-start="transform opacity-0 scale-95" x-transition:enter-end="transform opacity-100 scale-100" x-transition:leave="transition ease-in duration-75" x-transition:leave-start="transform opacity-100 scale-100" x-transition:leave-end="transform opacity-0 scale-95" class="origin-top-right absolute right-0 mt-2 w-48 rounded-md shadow-lg py-1 bg-white ring-1 ring-black ring-opacity-5 dark:bg-dark-gray-700 dark:shadow-highlight" role="menu" aria-orientation="vertical" aria-labelledby="user-menu" style="display: none;">

      <%= link_to "Edit User", edit_user_path(@user), class: "block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 dark:text-dark-gray-300 dark:hover:bg-dark-gray-600" %>
      <% if @user.locked_at.nil? %>
      	<%= link_to "Lock User Account", lock_user_users_path(lock_user_id: @user.id), class: "block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 dark:text-dark-gray-300 dark:hover:bg-dark-gray-600" %>
      <% else %>
      	<%= link_to "Unlock User Account", unlock_user_users_path(lock_user_id: @user.id), class: "block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 dark:text-dark-gray-300 dark:hover:bg-dark-gray-600" %>
      <% end %>

      <% if policy(:user).impersonate? %>
      	<%= link_to "Impersonate User", impersonate_user_path(@user), class: "block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 dark:text-dark-gray-300 dark:hover:bg-dark-gray-600", data:{ "turbo-method": "post"} %>
      <% end %>
    </div>
  </div>


  <div class="mt-4 flex-shrink-0 flex md:mt-0 md:ml-4">
    <%= link_to "Cancel", users_path, class:"inline-flex items-center px-4 py-2 border border-gray-300 rounded shadow-sm text-sm font-medium text-gray-700 bg-white hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-brand dark:bg-dark-gray-700 dark:text-dark-gray-300 dark:border-dark-gray-600 dark:focus:ring-offset-dark-gray-900 dark:ring-brand-dark" %>
  </div>
<% end %>

<div class="grid grid-cols-6 gap-4">

<div class="bg-white shadow overflow-hidden sm:rounded-lg col-span-6 lg:col-span-4 dark:bg-dark-gray-800 dark:shadow-highlight">
	<div class="px-4 py-5 sm:px-6">
		<h3 class="text-lg leading-6 font-medium text-gray-900 dark:text-dark-gray-300">
			Account
		</h3>
		<p class="mt-1 max-w-2xl text-sm text-gray-500 dark:text-dark-gray-400">
			<%= @user.email %> 
		</p>
	</div>
	<div class="border-t border-gray-200 dark:border-dark-gray-600">
		<dl>
			<div class="bg-gray-50 px-4 py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6 dark:bg-dark-gray-700">
				<dt class="text-sm font-medium text-gray-500 dark:text-dark-gray-400">
					User type
				</dt>
				<dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2 dark:text-dark-gray-300">
					<%= @user.user_type.titleize %>
				</dd>
			</div>
			<div class="bg-white px-4 py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6 dark:bg-dark-gray-800">
				<dt class="text-sm font-medium text-gray-500 dark:text-dark-gray-400">
					Title
				</dt>
				<dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2 dark:text-dark-gray-300">
					<%= @user.title %>
				</dd>
			</div>
			<div class="bg-gray-50 px-4 py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6 dark:bg-dark-gray-700 dark:text-dark-gray-400">
				<dt class="text-sm font-medium text-gray-500 dark:text-dark-gray-400">
					Ridings
				</dt>
				<dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2 dark:text-dark-gray-300">
					<% if @user.ridings.any? %>
						<% if @user.ridings.size == 338 %>
							<span class="italic font-medium">All ridings</span>
						<% else %>
						<ul>
							<% @user.user_ridings.each do |riding| %>
								<li><%= riding.riding.name %></li>
							<% end %>
						</ul>
						<% end %>
					<% else %>
						<span class="italic font-medium">No ridings</span>
					<% end %>
				</dd>
			</div>
			<div class="bg-white px-4 py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6 dark:bg-dark-gray-800">
				<dt class="text-sm font-medium text-gray-500 dark:text-dark-gray-400">
					Permissions
				</dt>
				<dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2 dark:text-dark-gray-300">
					<% if @user.user_permissions.any? %>
					<ul>
						<% @user.user_permissions.order(name: :asc).each do |permission| %>
							<li><%= permission.name %></li>
						<% end %>
					</ul>
					<% end %>
				</dd>
			</div>
		</dl>
	</div>
</div>

<div class="overflow-hidden sm:rounded-lg col-span-6 lg:col-span-2 h-auto">
	<section class="">
      <div class="bg-white px-4 py-5 shadow sm:rounded sm:px-6 dark:bg-dark-gray-800 dark:shadow-highlight">
        <h2 class="text-lg font-medium text-gray-900 dark:text-dark-gray-300">Details</h2>
        <div class="mt-2 flow-root space-y-6">
          <div class="">
            <div>
              <h2 class="text-sm font-medium text-gray-500 dark:text-dark-gray-400">Created</h2>
              <p class="text-sm font-medium text-gray-900 dark:text-dark-gray-300">
                <%= @user.created_at.strftime("%Y-%m-%d") %>  
              </p>
            </div>
          </div>

          <div class="">
            <div>
              <h2 class="text-sm font-medium text-gray-500 dark:text-dark-gray-400">Last sign in</h2>
              <p class="text-sm font-medium text-gray-900 dark:text-dark-gray-300">
                <% if @user.last_sign_in_at.present? %>
                  <%= @user.last_sign_in_at.strftime("%Y-%m-%d - %l:%M %p") %>
                <% else %>
                  Never
                <% end %>
              </p>
            </div>
          </div>

          <% if @user.locked_at.present? %>
	          <div class="">
	            <div>
	              <h2 class="text-sm font-medium text-gray-500 dark:text-dark-gray-400">Account Locked</h2>
	              <p class="text-sm font-medium text-gray-900 dark:text-dark-gray-300">
	                 <%= @user.locked_at.strftime("%Y-%m-%d - %l:%M %p") %>
	              </p>
	            </div>
	          </div>
          <% end %>

        </div>
      </div>
    </section>
</div>

</div>