config/routes.rb
Rails.application.routes.draw do
  resources :announcements
  resources :tools
  resources :user_permissions

  devise_for :users, controllers: {omniauth_callbacks: "users/omniauth_callbacks"}, :skip => [:registrations] 
  resources :users, :controller => "users" do
    collection do
      patch 'locale_switch'
      patch 'theme_switch'
      get 'lock_user'
      get 'unlock_user'
    end
    post :impersonate, on: :member
    post :stop_impersonating, on: :collection
  end
    
  resources :external_reports

  resources :ridings do
    resources :bank_balances, only: [:new, :create]

    get :voter_contact_stats_current, to: "voter_contact_stats#current"
    get :voter_contact_stats_yesterday, to: "voter_contact_stats#yesterday"
    get :voter_contact_stats_last_7, to: "voter_contact_stats#last_7"
    get :voter_contact_stats_last_30, to: "voter_contact_stats#last_30"

    get :volunteer_stats_current, to: "volunteer_stats#current"
    get :volunteer_stats_yesterday, to: "volunteer_stats#yesterday"
    get :volunteer_stats_last_7, to: "volunteer_stats#last_7"
    get :volunteer_stats_last_30, to: "volunteer_stats#last_30"
  end

  resources :reports, only: [:index] do
    collection do
      get :field_organizer
      get :regional_field
      get :fo_sort
    end
  end
  
  resources :notifications, only: [:index, :show]
  
  
  root "ridings#index"
end

app/views/shared/_mobile_nav.html.erb
<% if user_signed_in? %>
<nav class="h-full flex flex-col">
  <div class="space-y-1">
    <%= link_to ridings_path, class: "text-brand-light hover:bg-brand-dark hover:text-white group py-2 px-3 rounded-md flex items-center text-sm font-medium dark:text-dark-gray-300" do %>

      <svg class="text-brand-light group-hover:text-white mr-3 h-6 w-6 dark:text-dark-gray-400" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M17.657 16.657L13.414 20.9a1.998 1.998 0 01-2.827 0l-4.244-4.243a8 8 0 1111.314 0z" />
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 11a3 3 0 11-6 0 3 3 0 016 0z" />
      </svg>
      <span class=""><%= t("general.ridings") %></span>
    <% end %>

    <% if policy(:report).index? %>
      <%= link_to reports_path, class: "text-red-100 hover:bg-brand-dark hover:text-white group py-2 px-3 rounded-md flex items-center text-sm font-medium dark:text-dark-gray-300" do %>

        <svg class="text-brand-light group-hover:text-white mr-3 h-6 w-6 dark:text-dark-gray-400" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 17v-2m3 2v-4m3 4v-6m2 10H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
        </svg>
        <span class=""><%= t("general.reports") %></span>
      <% end %>
    <% end %>

    <%= link_to notifications_path, class: "text-red-100 hover:bg-brand-dark hover:text-white group py-2 px-3 rounded-md flex items-center text-sm font-medium dark:text-dark-gray-300" do %>

      <svg class="text-brand-light group-hover:text-white mr-3 h-6 w-6 dark:text-dark-gray-400" fill="none" viewBox="0 0 24 24" stroke="currentColor">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="1.9" d="M15 17h5l-1.405-1.405A2.032 2.032 0 0118 14.158V11a6.002 6.002 0 00-4-5.659V5a2 2 0 10-4 0v.341C7.67 6.165 6 8.388 6 11v3.159c0 .538-.214 1.055-.595 1.436L4 17h5m6 0v1a3 3 0 11-6 0v-1m6 0H9"></path>
      </svg>
      <span class=""><%= t("general.notifications") %></span>
      <span data-notifications-target="badge" class="hidden notifications-badge relative top-0 right-0 block h-2 w-2 transform -translate-y-1/2 translate-x-1/2 rounded-full text-white shadow-solid bg-brand group-hover:bg-white" id="mobile-notifications"></span>
    <% end %>

    <% if policy(:announcement).create? %>
      <%= link_to announcements_path, class: "text-red-100 hover:bg-brand-dark hover:text-white group py-2 px-3 rounded-md flex items-center text-sm font-medium dark:text-dark-gray-300" do %>

        <svg class="text-brand-light group-hover:text-white mr-3 h-6 w-6 dark:text-dark-gray-400" xmlns="http://www.w3.org/2000/svg" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M11 5.882V19.24a1.76 1.76 0 01-3.417.592l-2.147-6.15M18 13a3 3 0 100-6M5.436 13.683A4.001 4.001 0 017 6h1.832c4.1 0 7.625-1.234 9.168-3v14c-1.543-1.766-5.067-3-9.168-3H7a3.988 3.988 0 01-1.564-.317z" />
        </svg>
        <span class=""><%= t("general.announcements") %></span>
      <% end %>
    <% end %>

    <% if current_user.admin? %>
      <%= link_to external_reports_path, class: "text-red-100 hover:bg-brand-dark hover:text-white group py-2 px-3 rounded-md flex items-center text-sm font-medium dark:text-dark-gray-300" do %>

        <svg class="text-brand-light group-hover:text-white mr-3 h-6 w-6 dark:text-dark-gray-400" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10 6H6a2 2 0 00-2 2v10a2 2 0 002 2h10a2 2 0 002-2v-4M14 4h6m0 0v6m0-6L10 14" />
        </svg>
        <span class="">External Reports</span>
      <% end %>
    <% end %>

    <% if current_user.admin? %>
      <%= link_to tools_path, class: "text-red-100 hover:bg-brand-dark hover:text-white group py-2 px-3 rounded-md flex items-center text-sm font-medium dark:text-dark-gray-300" do %>

        <svg class="text-brand-light group-hover:text-white mr-3 h-6 w-6 dark:text-dark-gray-400" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10.325 4.317c.426-1.756 2.924-1.756 3.35 0a1.724 1.724 0 002.573 1.066c1.543-.94 3.31.826 2.37 2.37a1.724 1.724 0 001.065 2.572c1.756.426 1.756 2.924 0 3.35a1.724 1.724 0 00-1.066 2.573c.94 1.543-.826 3.31-2.37 2.37a1.724 1.724 0 00-2.572 1.065c-.426 1.756-2.924 1.756-3.35 0a1.724 1.724 0 00-2.573-1.066c-1.543.94-3.31-.826-2.37-2.37a1.724 1.724 0 00-1.065-2.572c-1.756-.426-1.756-2.924 0-3.35a1.724 1.724 0 001.066-2.573c-.94-1.543.826-3.31 2.37-2.37.996.608 2.296.07 2.572-1.065z" />
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 12a3 3 0 11-6 0 3 3 0 016 0z" />
        </svg>
        <span class="">Tools</span>
      <% end %>
    <% end %>
  </div>
</nav>
<% end %>

app/views/shared/_nav.html.erb
<div class="flex-shrink-0 flex items-center">
  <%= image_tag "logo.png", class: "h-10 w-10 round-full block" %>
</div>

<% if user_signed_in? %>
<div class="flex-1 mt-6 w-full px-2 space-y-1">
  <!-- Current: "bg-red-800 text-white", Default: "text-red-100 hover:bg-red-800 hover:text-white" -->

  <%= link_to ridings_path, class: "text-red-100 hover:bg-brand-dark hover:text-white group w-full p-3 rounded-md flex flex-col items-center text-xs font-medium dark:text-dark-gray-400 dark:hover:bg-dark-gray-900 dark:hover:text-dark-gray-300 nav-item", id:"ridings_menu" do %>

    <svg class="text-red-300 group-hover:text-white h-6 w-6 dark:text-brand-medium dark:group-hover:text-dark-gray-300" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
      <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M17.657 16.657L13.414 20.9a1.998 1.998 0 01-2.827 0l-4.244-4.243a8 8 0 1111.314 0z" />
      <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 11a3 3 0 11-6 0 3 3 0 016 0z" />
    </svg>
    <span class="mt-2"><%= t("general.ridings") %></span>
  <% end %>

  <% if policy(:report).index? %>
    <%= link_to reports_path, class: "text-red-100 hover:bg-brand-dark hover:text-white group w-full p-3 rounded-md flex flex-col items-center text-xs font-medium dark:text-dark-gray-400 dark:hover:bg-dark-gray-900 dark:hover:text-dark-gray-300 nav-item", id:"reports_menu" do %>

      <svg class="text-red-300 group-hover:text-white h-6 w-6 dark:text-brand-medium dark:group-hover:text-dark-gray-300" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 17v-2m3 2v-4m3 4v-6m2 10H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
      </svg>
      <span class="mt-2"><%= t("general.reports") %></span>
    <% end %>
  <% end %>

  <% if current_user.admin? %>
    <div class="items-center">
      <hr class="mt-5 border-t border-red-700 dark:border-dark-gray-600" aria-hidden="true">
      <p class="mt-3 mb-5 text-center mx-auto px-3 text-xs font-medium text-brand-dark uppercase tracking-wider dark:text-dark-gray-500">
        Admin
      </p>
    </div>
  <% end %>

  <% if current_user.admin? %>
    <%= link_to announcements_path, class: "text-red-100 hover:bg-brand-dark hover:text-white group w-full p-3 rounded-md flex flex-col items-center text-xs font-medium dark:text-dark-gray-400 dark:hover:bg-dark-gray-900 dark:hover:text-dark-gray-300" do %>

      <svg class="text-red-300 group-hover:text-white h-6 w-6 dark:text-brand-medium dark:group-hover:text-dark-gray-300" xmlns="http://www.w3.org/2000/svg" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M11 5.882V19.24a1.76 1.76 0 01-3.417.592l-2.147-6.15M18 13a3 3 0 100-6M5.436 13.683A4.001 4.001 0 017 6h1.832c4.1 0 7.625-1.234 9.168-3v14c-1.543-1.766-5.067-3-9.168-3H7a3.988 3.988 0 01-1.564-.317z" />
      </svg>

      <span class="mt-2 text-center"><%= t("general.announcements") %></span>
    <% end %>
  <% end %>

  <% if current_user.admin? %>
    <%= link_to external_reports_path, class: "text-red-100 hover:bg-brand-dark hover:text-white group w-full p-3 rounded-md flex flex-col items-center text-xs font-medium dark:text-dark-gray-400 dark:hover:bg-dark-gray-900 dark:hover:text-dark-gray-300" do %>

      <svg class="text-red-300 group-hover:text-white h-6 w-6 dark:text-brand-medium dark:group-hover:text-dark-gray-300" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10 6H6a2 2 0 00-2 2v10a2 2 0 002 2h10a2 2 0 002-2v-4M14 4h6m0 0v6m0-6L10 14" />
      </svg>
      <span class="mt-2 text-center"><%= t("general.external_reports") %></span>
    <% end %>
  <% end %>

  <% if current_user.admin? %>
    <%= link_to tools_path, class: "text-red-100 hover:bg-brand-dark hover:text-white group w-full p-3 rounded-md flex flex-col items-center text-xs font-medium dark:text-dark-gray-400 dark:hover:bg-dark-gray-900 dark:hover:text-dark-gray-300" do %>

      <svg class="text-red-300 group-hover:text-white h-6 w-6 dark:text-brand-medium dark:group-hover:text-dark-gray-300" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10.325 4.317c.426-1.756 2.924-1.756 3.35 0a1.724 1.724 0 002.573 1.066c1.543-.94 3.31.826 2.37 2.37a1.724 1.724 0 001.065 2.572c1.756.426 1.756 2.924 0 3.35a1.724 1.724 0 00-1.066 2.573c.94 1.543-.826 3.31-2.37 2.37a1.724 1.724 0 00-2.572 1.065c-.426 1.756-2.924 1.756-3.35 0a1.724 1.724 0 00-2.573-1.066c-1.543.94-3.31-.826-2.37-2.37a1.724 1.724 0 00-1.065-2.572c-1.756-.426-1.756-2.924 0-3.35a1.724 1.724 0 001.066-2.573c-.94-1.543.826-3.31 2.37-2.37.996.608 2.296.07 2.572-1.065z" />
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 12a3 3 0 11-6 0 3 3 0 016 0z" />
      </svg>

      <span class="mt-2"><%= t("general.tools") %></span>
    <% end %>
  <% end %>

  <% if current_user.admin? %>
    <%= link_to user_permissions_path, class: "text-red-100 hover:bg-brand-dark hover:text-white group w-full p-3 rounded-md flex flex-col items-center text-xs font-medium dark:text-dark-gray-400 dark:hover:bg-dark-gray-900 dark:hover:text-dark-gray-300" do %>

      <svg class="text-red-300 group-hover:text-white h-6 w-6 dark:text-brand-medium dark:group-hover:text-dark-gray-300" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 15v2m-6 4h12a2 2 0 002-2v-6a2 2 0 00-2-2H6a2 2 0 00-2 2v6a2 2 0 002 2zm10-10V7a4 4 0 00-8 0v4h8z" />
      </svg>
      <span class="mt-2"><%= t("general.permissions") %></span>
    <% end %>
  <% end %>

  <% if current_user.admin? %>
    <%= link_to users_path, class: "text-red-100 hover:bg-brand-dark hover:text-white group w-full p-3 rounded-md flex flex-col items-center text-xs font-medium dark:text-dark-gray-400 dark:hover:bg-dark-gray-900 dark:hover:text-dark-gray-300" do %>

      <svg class="text-red-300 group-hover:text-white h-6 w-6 dark:text-brand-medium dark:group-hover:text-dark-gray-300" xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 4.354a4 4 0 110 5.292M15 21H3v-1a6 6 0 0112 0v1zm0 0h6v-1a6 6 0 00-9-5.197M13 7a4 4 0 11-8 0 4 4 0 018 0z" />
      </svg>
      <span class="mt-2"><%= t("general.users") %></span>
    <% end %>
  <% end %>
</div>
<% end %>

app/views/shared/_notifications.html.erb
<%= tag.div class: "hidden z-10 md:inline-flex items-center align-middle leading-none rounded no-underline text-gray-700 hover:text-gray-800 hover:bg-white",
  data: {
    controller: "notifications",
    notifications_account_unread_value: @account_unread,
    notifications_total_unread_value: @total_unread,
  }, id: "notifications_nav" do %>

  <div class="relative" data-controller="dropdown">
    <%# Marks all notifications as read when menu opens by default. Remove the notifications Stimulus actions to disable this. %>
    <%= tag.button class: "group p-1 rounded text-sm text-brand-medium font-bold hover:text-white hover:bg-brand dark:text-dark-gray-300 dark:hover:bg-brand-dark",
      aria: { label: "Notifications" },
      data: {
        action: "click->notifications#open touch->notifications#open click->dropdown#toggle click@window->dropdown#hide touch->dropdown#toggle touch@window->dropdown#hide"
      } do %>
      <span class="appearance-none flex items-center inline-block relative">
        <svg class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="1.9" d="M15 17h5l-1.405-1.405A2.032 2.032 0 0118 14.158V11a6.002 6.002 0 00-4-5.659V5a2 2 0 10-4 0v.341C7.67 6.165 6 8.388 6 11v3.159c0 .538-.214 1.055-.595 1.436L4 17h5m6 0v1a3 3 0 11-6 0v-1m6 0H9"></path>
        </svg>
        <span data-notifications-target="badge" class="hidden absolute top-px right-1 block h-2 w-2 transform -translate-y-1/2 translate-x-1/2 rounded-full text-white shadow-solid bg-brand group-hover:bg-white"></span>
      </span>
    <% end %>

    <div data-dropdown-target="menu" class="lg:absolute lg:right-0 mt-2 hidden z-20">
      <div class="bg-white shadow rounded-md border border-gray-200 overflow-hidden sm:w-96 dark:bg-dark-gray-800 dark:border-dark-gray-600">
        <%= turbo_frame_tag "notifications", loading: :lazy, target: :_top, src: notifications_path, data: { notifications_target: "list" } do %>
          <p class="p-4"><i class="fas fa-circle-notch fa-spin text-gray-400 mr-1"></i> Loading...</p>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

app/views/shared/_profile_dropdown.html.erb
<!-- Profile dropdown -->
<% if user_signed_in? %>
  <div x-data="{ open: false }" @keydown.window.escape="open = false" @click.away="open = false", class="relative flex-shrink-0">

    <div>
      <button @click="open = !open" type="button" class="rounded-full flex text-sm focus:outline-none focus:ring-2 ring-brand-medium" id="user-menu-button" aria-haspopup="true" x-bind:aria-expanded="open">
        <span class="sr-only">Open user menu</span>
        <svg xmlns="http://www.w3.org/2000/svg" class="rounded-full h-8 w-8 text-brand dark:text-dark-gray-300" fill="none" viewBox="0 0 24 24" stroke="currentColor">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5.121 17.804A13.937 13.937 0 0112 16c2.5 0 4.847.655 6.879 1.804M15 10a3 3 0 11-6 0 3 3 0 016 0zm6 2a9 9 0 11-18 0 9 9 0 0118 0z" />
        </svg>
      </button>
    </div>

    <!--
      Dropdown menu, show/hide based on menu state.

      Entering: "transition ease-out duration-100"
        From: "transform opacity-0 scale-95"
        To: "transform opacity-100 scale-100"
      Leaving: "transition ease-in duration-75"
        From: "transform opacity-100 scale-100"
        To: "transform opacity-0 scale-95"
    -->
    <div x-show="open" x-description="Profile dropdown panel, show/hide based on dropdown state." x-transition:enter="transition ease-out duration-100" x-transition:enter-start="transform opacity-0 scale-95" x-transition:enter-end="transform opacity-100 scale-100" x-transition:leave="transition ease-in duration-75" x-transition:leave-start="transform opacity-100 scale-100" x-transition:leave-end="transform opacity-0 scale-95" class="origin-top-right absolute right-0 mt-2 w-48 rounded-md shadow-lg pb-1 bg-white ring-1 ring-black ring-opacity-5 divide-y divide-gray-300 dark:bg-dark-gray-700 dark:divide-dark-gray-600" role="menu" aria-orientation="vertical" aria-labelledby="user-menu" style="display: none;">
      <div class="px-4 py-3 bg-gray-100 rounded-t-md dark:bg-dark-gray-800 dark:shadow-highlight" role="none">
        <p class="text-sm font-medium text-gray-900 truncate dark:text-dark-gray-300" role="none">
          <%= current_user.first_name %> <%= current_user.last_name %>
        </p>
        <p class="text-sm font-base text-gray-900 truncate dark:text-dark-gray-300" role="none">
          <%= current_user.email %>
        </p>
      </div>

      <div class="py-1" role="none">

      <%= link_to t("general.announcements"), announcements_path, class: "text-gray-700 block px-4 py-2 text-sm hover:bg-gray-100 w-full text-left dark:text-dark-gray-300 dark:hover:bg-dark-gray-600" %>

      <%= button_to(t("general.logout"), destroy_user_session_path, method: :delete, class: "text-gray-700 block px-4 py-2 text-sm hover:bg-gray-100 w-full text-left dark:text-dark-gray-300 dark:hover:bg-dark-gray-600", role: "menuitem", data: {turbo: false}) %>
    </div>
    </div>
  </div>
<% end %>

app/views/shared/_volunteer_filter_buttons.html.erb
<span class="mt-2 sm:mt-0 sm:ml-6 relative z-0 inline-flex shadow-sm rounded-md">
  <%= link_to "Current", riding_volunteer_stats_current_path(@riding), class:"relative inline-flex items-center px-2 py-1 rounded-l-md border border-gray-300 bg-white text-xs font-medium text-gray-700 hover:bg-gray-50 focus:z-10 focus:outline-none focus:ring-1 focus:ring-brand focus:border-brand dark:bg-dark-gray-800 dark:border-dark-gray-600 dark:text-dark-gray-300 dark:hover:bg-dark-gray-700 #{'selected_button' if selected == 'current'}" %>

  <%= link_to "Yesterday", riding_volunteer_stats_yesterday_path(@riding), class:"-ml-px relative inline-flex items-center px-2 py-1 border border-gray-300 bg-white text-xs font-medium text-gray-700 hover:bg-gray-50 focus:z-10 focus:outline-none focus:ring-1 focus:ring-brand focus:border-brand dark:bg-dark-gray-800 dark:border-dark-gray-600 dark:text-dark-gray-300 dark:hover:bg-dark-gray-700 #{'selected_button' if selected == 'yesterday'}" %>

   <%= link_to "Last 7 Days", riding_volunteer_stats_last_7_path(@riding), class:"-ml-px relative inline-flex items-center px-2 py-1 border border-gray-300 bg-white text-xs font-medium text-gray-700 hover:bg-gray-50 focus:z-10 focus:outline-none focus:ring-1 focus:ring-brand focus:border-brand dark:bg-dark-gray-800 dark:border-dark-gray-600 dark:text-dark-gray-300 dark:hover:bg-dark-gray-700 #{'selected_button' if selected == 'last_7'}" %>

    <%= link_to "Last 30 Days", riding_volunteer_stats_last_30_path(@riding), class:"-ml-px relative inline-flex items-center px-2 py-1 rounded-r-md border border-gray-300 bg-white text-xs font-medium text-gray-700 hover:bg-gray-50 focus:z-10 focus:outline-none focus:ring-1 focus:ring-brand focus:border-brand dark:bg-dark-gray-800 dark:border-dark-gray-600 dark:text-dark-gray-300 dark:hover:bg-dark-gray-700 #{'selected_button' if selected == 'last_30'}" %>
</span>

app/views/shared/_voter_contact_filter_buttons.html.erb
<span class="mt-2 sm:mt-0 sm:ml-6 relative z-0 inline-flex shadow-sm rounded-md">
  <%= link_to "Current", riding_voter_contact_stats_current_path(@riding), class:"relative inline-flex items-center px-2 py-1 rounded-l-md border border-gray-300 bg-white text-xs font-medium text-gray-700 hover:bg-gray-50 focus:z-10 focus:outline-none focus:ring-1 focus:ring-brand focus:border-brand dark:bg-dark-gray-800 dark:border-dark-gray-600 dark:text-dark-gray-300 dark:hover:bg-dark-gray-700 #{'selected_button' if selected == 'current'}" %>

  <%= link_to "Yesterday", riding_voter_contact_stats_yesterday_path(@riding), class:"-ml-px relative inline-flex items-center px-2 py-1 border border-gray-300 bg-white text-xs font-medium text-gray-700 hover:bg-gray-50 focus:z-10 focus:outline-none focus:ring-1 focus:ring-brand focus:border-brand dark:bg-dark-gray-800 dark:border-dark-gray-600 dark:text-dark-gray-300 dark:hover:bg-dark-gray-700 #{'selected_button' if selected == 'yesterday'}" %>

   <%= link_to "Last 7 Days", riding_voter_contact_stats_last_7_path(@riding), class:"-ml-px relative inline-flex items-center px-2 py-1 border border-gray-300 bg-white text-xs font-medium text-gray-700 hover:bg-gray-50 focus:z-10 focus:outline-none focus:ring-1 focus:ring-brand focus:border-brand dark:bg-dark-gray-800 dark:border-dark-gray-600 dark:text-dark-gray-300 dark:hover:bg-dark-gray-700 #{'selected_button' if selected == 'last_7'}" %>

    <%= link_to "Last 30 Days", riding_voter_contact_stats_last_30_path(@riding), class:"-ml-px relative inline-flex items-center px-2 py-1 rounded-r-md border border-gray-300 bg-white text-xs font-medium text-gray-700 hover:bg-gray-50 focus:z-10 focus:outline-none focus:ring-1 focus:ring-brand focus:border-brand dark:bg-dark-gray-800 dark:border-dark-gray-600 dark:text-dark-gray-300 dark:hover:bg-dark-gray-700 #{'selected_button' if selected == 'last_30'}" %>
</span>